## -----------------------------------------------------------------------------
##
## Copyright (C) 2022 CERN, TUM, and UT Austin. All Rights Reserved.
##
## Licensed under the Apache License, Version 2.0 (the "License");
## you may not use this file except in compliance with the License.
##
## See the LICENSE file distributed with this work for details.
## See the NOTICE file distributed with this work for additional information
## regarding copyright ownership.
##
## Authored by: Tobias Duswald, CERN, TUM
##
## -----------------------------------------------------------------------------

name: repository-check

on:
  push:

jobs:
  code-style:
    runs-on: ubuntu-20.04

    steps:

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install clang-format
        pip install black

    - name: Checkout this repository
      uses: actions/checkout@v2

    - name: Run code style check
      run: |
        ./style_check.sh
